// HuC6280 single-step tests from the SingleStepTests project (Mesen-generated):
//
//     https://github.com/SingleStepTests/huc6280
//
// Each test exercises a single opcode and provides the full CPU + memory state
// before and after. The suite models memory as a flat 2 MB physical space with
// the HuC6280 MMU performing the usual MPR translation, so addresses in the
// JSON are *physical*.
//
// This emulator's core only ever emits *logical* 16-bit addresses, so we run
// the tests through a translating bus ([`PhysBus`]) that maps each logical
// access to a physical address using a shadow copy of the mapping registers
// (MPR0-MPR7). This lets us validate the variant without widening the core's
// `Bus` trait.
//
// ## Getting the test data
//
// The JSON is not vendored (it is hundreds of MB once expanded). Fetch and
// transcode it once:
//
//     git clone https://github.com/SingleStepTests/huc6280 /tmp/huc6280
//     (cd /tmp/huc6280 && python3 transcode_json.py)   # .json.bin -> .json
//     HUC6280_TESTS=/tmp/huc6280/v1 cargo test --test single_step_huc6280
//
// If the directory is absent the test prints instructions and passes, so it
// never breaks a checkout that lacks the (large) data set.
//
// ## Known gaps
//
// The reference suite is generated by Mesen and exercises full hardware
// accuracy, including a couple of HuC6280 traits this core does not yet model:
//
//   * The `T` (memory-operation) flag, which redirects ORA/AND/EOR/ADC and
//     friends to operate on memory instead of the accumulator. Roughly half of
//     each affected opcode's tests set `T`, and those diverge.
//   * Block-transfer instructions (TII/TDD/TIN/TIA/TAI) stash A/X/Y into the
//     stack region and are cycle-interruptible.
//   * Exact per-instruction cycle counts.
//
// The zero page ($2000-$20FF), stack ($2100-$21FF), and BRK vector ($FFF6) are
// now modelled, so the standard load/store/stack/branch opcodes pass.
//
// Accordingly, this test asserts 100% correctness only for the opcodes listed
// in `FULLY_MODELLED` (which avoid the gaps above) and reports pass rates for
// everything else without failing, so it stays useful as the core improves.

use mos6502::cpu::CPU;
use mos6502::instruction::Huc6280;
use mos6502::memory::Bus;
use mos6502::registers::{StackPointer, Status, map_physical_address};
use serde::Deserialize;
use std::path::{Path, PathBuf};

const PHYS_SIZE: usize = 2 * 1024 * 1024; // 2 MB physical address space
const PHYS_MASK: usize = PHYS_SIZE - 1;

/// A bus that stores a flat 2 MB physical memory and translates the logical
/// 16-bit addresses emitted by the CPU through a shadow of the mapping
/// registers, exactly as the HuC6280 MMU does.
struct PhysBus {
    ram: Vec<u8>,
    mpr: [u8; 8],
}

impl PhysBus {
    fn new(mpr: [u8; 8]) -> Self {
        Self {
            ram: vec![0; PHYS_SIZE],
            mpr,
        }
    }

    fn phys(&self, logical: u16) -> usize {
        // Reuse the core's canonical mapping formula instead of re-deriving it.
        map_physical_address(&self.mpr, logical) as usize & PHYS_MASK
    }
}

impl Bus for PhysBus {
    fn get_byte(&mut self, address: u16) -> u8 {
        let p = self.phys(address);
        self.ram[p]
    }

    fn set_byte(&mut self, address: u16, value: u8) {
        let p = self.phys(address);
        self.ram[p] = value;
    }

    fn set_mapping_register(&mut self, index: usize, value: u8) {
        // Stay in sync with TAM writes automatically; no post-step shadow copy.
        self.mpr[index] = value;
    }
}

#[derive(Deserialize)]
struct State {
    #[serde(rename = "A")]
    a: u8,
    #[serde(rename = "X")]
    x: u8,
    #[serde(rename = "Y")]
    y: u8,
    #[serde(rename = "S")]
    s: u8,
    #[serde(rename = "P")]
    p: u8,
    #[serde(rename = "PC")]
    pc: u16,
    #[serde(rename = "MPR")]
    mpr: [u8; 8],
    #[serde(rename = "RAM")]
    ram: Vec<(u32, u8)>,
}

#[derive(Deserialize)]
struct Test {
    name: String,
    initial: State,
    #[serde(rename = "final")]
    final_state: State,
}

/// Bit 5 of the status byte is the HuC6280 `T` (memory-operation) flag, which
/// this emulator does not model (it treats that bit as the 6502 "unused" bit).
/// Mask it out of status comparisons. Everything else (N V B D I Z C) is
/// compared exactly.
const STATUS_COMPARE_MASK: u8 = !Status::PS_UNUSED.bits();

fn run_one(test: &Test) -> Result<(), String> {
    let mut cpu = CPU::new(PhysBus::new(test.initial.mpr), Huc6280);

    // Load the initial CPU register state.
    cpu.registers.accumulator = test.initial.a;
    cpu.registers.index_x = test.initial.x;
    cpu.registers.index_y = test.initial.y;
    cpu.registers.stack_pointer = StackPointer(test.initial.s);
    cpu.registers.program_counter = test.initial.pc;
    cpu.registers.status = Status::from_bits_retain(test.initial.p);
    cpu.registers.mpr = test.initial.mpr;

    // Seed physical memory.
    for &(addr, val) in &test.initial.ram {
        cpu.memory.ram[addr as usize & PHYS_MASK] = val;
    }

    // Execute exactly one instruction (no interrupt servicing).
    match cpu.fetch_next_and_decode() {
        Some(decoded) => cpu.execute_instruction(decoded),
        None => return Err("opcode not decoded by the Huc6280 variant".to_string()),
    }

    // Compare the resulting register file.
    let mut diffs = Vec::new();
    let reg = &cpu.registers;
    if reg.accumulator != test.final_state.a {
        diffs.push(format!(
            "A {:#04x}!={:#04x}",
            reg.accumulator, test.final_state.a
        ));
    }
    if reg.index_x != test.final_state.x {
        diffs.push(format!(
            "X {:#04x}!={:#04x}",
            reg.index_x, test.final_state.x
        ));
    }
    if reg.index_y != test.final_state.y {
        diffs.push(format!(
            "Y {:#04x}!={:#04x}",
            reg.index_y, test.final_state.y
        ));
    }
    if reg.stack_pointer.0 != test.final_state.s {
        diffs.push(format!(
            "S {:#04x}!={:#04x}",
            reg.stack_pointer.0, test.final_state.s
        ));
    }
    if reg.program_counter != test.final_state.pc {
        diffs.push(format!(
            "PC {:#06x}!={:#06x}",
            reg.program_counter, test.final_state.pc
        ));
    }
    let got_p = reg.status.bits() & STATUS_COMPARE_MASK;
    let want_p = test.final_state.p & STATUS_COMPARE_MASK;
    if got_p != want_p {
        diffs.push(format!("P {got_p:#010b}!={want_p:#010b}"));
    }
    if reg.mpr != test.final_state.mpr {
        diffs.push(format!("MPR {:?}!={:?}", reg.mpr, test.final_state.mpr));
    }

    // Compare every memory cell the test cares about.
    for &(addr, val) in &test.final_state.ram {
        let got = cpu.memory.ram[addr as usize & PHYS_MASK];
        if got != val {
            diffs.push(format!("mem[{addr:#08x}] {got:#04x}!={val:#04x}"));
        }
    }

    if diffs.is_empty() {
        Ok(())
    } else {
        Err(diffs.join(", "))
    }
}

/// Opcodes this core models accurately enough to require a perfect score.
///
/// These avoid the known gaps documented at the top of the file (the T flag and
/// block transfers): the HuC6280 register/MMU helpers, plus the standard
/// load/stack/branch/jump opcodes whose relocated zero page and stack are now
/// handled. Every entry has been verified at 2500/2500 against the suite.
const FULLY_MODELLED: &[u8] = &[
    0x02, // SXY
    0x20, // JSR
    0x22, // swap A,X
    0x42, // SAY
    0x48, // PHA
    0x53, // TAM
    0x60, // RTS
    0x62, // CLA
    0x82, // CLX
    0x83, // TST #imm, zp
    0xA1, // LDA (zp,X)
    0xA5, // LDA zp
    0xA9, // LDA #imm (sanity check)
    0xB1, // LDA (zp),Y
    0xC2, // CLY
    0xEA, // NOP
];
// Note: TMA ($43) is deliberately excluded. Its defined behaviour (a non-zero
// mask, wired-OR of the selected mapping registers) is correct, but the suite
// also covers the `mask == 0` case, which leaves an undefined open-bus value in
// the accumulator that is not worth reproducing.

fn opcode_from_stem(stem: &str) -> Option<u8> {
    u8::from_str_radix(stem, 16).ok()
}

fn tests_dir() -> PathBuf {
    std::env::var("HUC6280_TESTS")
        .map(PathBuf::from)
        .unwrap_or_else(|_| Path::new("tests/huc6280/v1").to_path_buf())
}

#[test]
fn huc6280_single_step_tests() {
    let dir = tests_dir();
    if !dir.is_dir() {
        eprintln!(
            "skipping: no HuC6280 test data at {}.\n\
             Download it with:\n  \
             git clone https://github.com/SingleStepTests/huc6280 /tmp/huc6280\n  \
             (cd /tmp/huc6280 && python3 transcode_json.py)\n  \
             HUC6280_TESTS=/tmp/huc6280/v1 cargo test --test single_step_huc6280",
            dir.display()
        );
        return;
    }

    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("read test dir")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|e| e == "json"))
        .collect();
    files.sort();

    assert!(
        !files.is_empty(),
        "no *.json files in {} (did you run transcode_json.py?)",
        dir.display()
    );

    let mut total = 0usize;
    let mut passed = 0usize;
    let mut supported_failures: Vec<String> = Vec::new();

    for path in &files {
        let data = std::fs::read_to_string(path).expect("read json");
        let tests: Vec<Test> = serde_json::from_str(&data).expect("parse json");

        let mut op_total = 0usize;
        let mut op_passed = 0usize;
        let mut first_failure: Option<String> = None;

        for test in &tests {
            op_total += 1;
            match run_one(test) {
                Ok(()) => op_passed += 1,
                Err(reason) => {
                    if first_failure.is_none() {
                        first_failure = Some(format!("{}: {}", test.name, reason));
                    }
                }
            }
        }

        total += op_total;
        passed += op_passed;

        let name = path.file_stem().unwrap().to_string_lossy();
        let opcode = opcode_from_stem(&name);
        let modelled = opcode.is_some_and(|op| FULLY_MODELLED.contains(&op));
        let tag = if modelled { " [modelled]" } else { "" };

        if op_passed == op_total {
            println!("opcode {name}: {op_passed}/{op_total} OK{tag}");
        } else {
            println!(
                "opcode {name}: {op_passed}/{op_total}{tag} -- first failure: {}",
                first_failure.as_deref().unwrap_or("?")
            );
            if modelled {
                supported_failures.push(format!(
                    "{name} ({op_passed}/{op_total}): {}",
                    first_failure.as_deref().unwrap_or("?")
                ));
            }
        }
    }

    println!(
        "\nHuC6280 single-step summary: {passed}/{total} passed across {} opcode file(s)",
        files.len()
    );

    assert!(
        supported_failures.is_empty(),
        "fully-modelled opcode(s) regressed:\n  {}",
        supported_failures.join("\n  ")
    );
}
