name: CI
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    types:
      - opened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo fmt (check if all code is rustfmt-ed)
        run: cargo fmt --all -- --check
      - name: Run cargo clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run cargo-audit
        run: cargo audit --deny yanked

  publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo fetch
        run: cargo fetch
      - name: cargo publish (dry run)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --dry-run

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
      - lint
      - audit
      - publish-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: cargo fetch
        run: cargo fetch
      - name: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
